# Site settings
# https://github.com/robwierzbowski/jekyll-picture-tag
title: Developing with Swift, Objective-C, Rails
email: tisunov.pavel@gmail.com
description: > #iOS, Rails developer, geeking out about software, business, life, travel and snowboarding
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tisunov.com" # the base hostname & protocol for your site
twitter_username: ptisunov
github_username:  tisunov
highlighter: rouge #pygments

# Redcarpet gives you github style fenced code blocks using triple-backtick notation.
# redcarpet
markdown: kramdown

kramdown:
  syntax_highlighter: rouge#pygments